apiVersion: apps/v1
kind: Deployment
metadata:
  name: tssdata01
  labels:
    app: tssdata01
spec:
  selector:
    matchLabels:
      app: tssdata01
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: tssdata01
    spec:
      containers:
      - name: tssdata-web01
        image: {{ .Values.image }}
        volumeMounts:
        - name: config-vol
          mountPath: /opt
        ports:
        - containerPort: 8000
      volumes:
        - name: config-vol
        configMap:
          name: {{ .Values.configmap.data.name }}
